version: 0.2

phases:
  install:
    runtime-version:
      java: corretto11
  pre_build:
    commands:
      - echo skipped on `date`
  build:
    commands:
      - echo Build started on `date`
      - gradle build
      - gradle assemble
      - echo Build finished on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'build/libs/*.jar'