version: 0.2

phases:
  install:
    runtime-version:
      java: corretto11
  pre-build:
    commands:
      - echo skipped on `date`
  build:
    comamnds:
      - echo gradle clean build assemble on `date`
      - java -version
  post-build:
    commands:
      - echo Build completed on `date`
  artifacts:
    files:
      - build/libs/*.jar