version: 0.2

phases:
  install:
    runtime-version:
      java: corretto11
  pre_build:
    commands:
      - echo skipped on `date`
  build:
    comamnds:
      - echo gradle clean build assemble on `date`
      - java -version
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/*.jar