micronaut:
  server:
    port: ${HTTP_PORT:8085}
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:2377168}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:MySQL8Dialect}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: true

endpoints:
  all:
    sensitive: true
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous

grpc:
  server:
    health:
      enabled: true
