micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 2377168
    schema-generate: CREATE_DROP
    dialect: MYSQL8Dialect

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: true




